### ISSUE TITLE
[Feature check] Garmin Fenix 5 compatibility

### ISSUE THREAD

**Issue by putti23** [inonoob/pirowflo#20]
I have got Fenix 5 and garmin usb dongle .
I have problem to add pirowflo as a sensor in my watch. It doesn't see any sensor.
Maybe pirowflo works only with with fenix 6. 
In logs i can see:
2021-02-15 18:25:47,930 - __main__ - INFO - Start Ant and start broadcast data
start search for dongle
2021-02-15 18:25:48,016 - smartrowreader - INFO - starting discovery
2021-02-15 18:25:48,067 - waterrowerble - INFO - Registering GATT application...
2021-02-15 18:25:48,187 - ble - INFO - GetManagedObjects
2021-02-15 18:25:48,209 - ble - INFO - GetAll
2021-02-15 18:25:48,222 - ble - INFO - returning props
2021-02-15 18:25:48,265 - waterrowerble - INFO - GATT application registered
2021-02-15 18:25:48,272 - waterrowerble - INFO - Advertisement registered
calibration
set Networkkey:b'\x00\xb9\xa5!\xfb\xbdr\xc3E'
create Channel
----
I checked on fenix 5 and germin edhe 830. with no success.
---
Is it Bug or works only with fenix 6 ?

**Comment by inonoob** [comment]
Hey 

I got the feedback that it works for the Fenix 6 with smartrow and S4 monitor. You can check if your dongle is working with the Android app ant+ plugin sampler or ipsensorman. You need to attach the dongle to your phone via org cable. 

If you can add it to your watch then you can try ergiq to see if you can connect.

**Comment by inonoob** [comment]
Do you have some news for me ?

**Comment by inonoob** [comment]
I just check a bit for garmin and you must ensure that the Garmin product support the following: 

- FE-C or FE support either

If it does then you can try make it work with the watch. I have the same issue as my Vivoactive 3 has no Ant+ profile on it to interact with fitness equipments

**Comment by putti23** [comment]
Fenix5 doesn’t have FE-C ;-( 

 

 

Od: inonoob <notifications@github.com> 
Wysłano: wtorek, 16 lutego 2021 12:41
Do: inonoob/pirowflo <pirowflo@noreply.github.com>
DW: putek@onet.pl; Author <author@noreply.github.com>
Temat: Re: [inonoob/pirowflo] [Feature check] Garmin Fenix 5 compatibility (#20)

 

I just check a bit for garmin and you must ensure that the Garmin product support the following:

*	FE-C or FE support either

If it does then you can try make it work with the watch. I have the same issue as my Vivoactive 3 has no Ant+ profile on it to interact with fitness equipments

**Comment by inonoob** [comment]
But if you still Interested, we could see if we can get the Garmin 830 running as it has the FE-C and FE support

**Comment by inonoob** [comment]
Closed no feedback
