### ISSUE TITLE
Kinomap working with SmartRow 3.0 on IOS

### ISSUE THREAD

**Issue by DANgerous25** [inonoob/pirowflo#53]
Hi, thanks to your latest work with @dan06 my PiRoFlow is working with my new SmartRow. I notice on your homepage it says Kinomap is "Pending Test". I've done a very quick test after getting everything working, it appears to work in that Kinomap gets the SmartRow values and these are displayed continually in the app. Hence I think you can mark it with a tick.

**Comment by inonoob** [comment]
Hey

you are welcome. Hope you have fun and can enjoy the full potential of the smartrow.

One question: For which OS did it work apple or android ?

**Comment by DANgerous25** [comment]
IOS. Thanks a lot.

**Comment by inonoob** [comment]
Thanks for your feedback !

**Comment by inonoob** [comment]
Will update the readme
